# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# 本文件是首次 commit 时手写的占位版。首次部署到 Orion O6N 后，
# 建议在目标机器上运行 `nixos-generate-config --show-hardware-config > /etc/nixos/hardware-configuration.nix`
# 然后把生成的真实内容覆盖回本文件。
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ── 平台 ──────────────────────────────────────────────────────────
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # ── initrd 模块（首次部署后由 nixos-generate-config 自动填充）─────
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # 文件系统由 ./disko.nix 接管，无需在此声明 fileSystems
  # 引导由 hardware.radxa 模块（radxa-orion-o6）处理，无需在此声明 boot.loader
}
